#!/bin/bash
#SBATCH -J hsc_stripes
#SBATCH -A desi
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -N 1
#SBATCH -c 256
#SBATCH -t 03:00:00
#SBATCH -o hsc_stripes_%j.out
# Anneal an HSC MBQ1 tiling of the DESI Run 2 Niji stripes (rectangular footprint,
# data/subaru3/niji_stripes_2p8_hsc.csv: the 2.8-deg bands with the RA bounds trimmed
# to the HSC-Niji wide footprint) against the data/subaru3 throughput model.
#
#   sbatch nersc/anneal_hsc_stripes.sh [POWER] [ITERS] [PREFIX] [RECTS]
#
# POWER is the exponent of the rms/mean^power objective (default 1; 0 would be
# the plain variance objective that let earlier solutions spill outside the
# footprint), ITERS defaults to 300, PREFIX to stripes_p<POWER>_.
# Start: a 1.299 x 1.125 deg lattice of pointing centres (the HSC-SSP Wide
# spacing) fitted to each 5.6-deg band, x Atsushi's four phase-1 dither
# offsets = 2548 tiles, 4 rotations each.  RECTS (default
# data/subaru3/niji_stripes_2p8_hsc.csv) can name another rectangle file.  Output in $SCRATCH/skytiling/hsc_stripes/.
set -e
REPO=${SKYTILING_REPO:-${SLURM_SUBMIT_DIR:-$(cd "$(dirname "$0")/.." && pwd)}}   # submit from the repo root
if [ ! -f "$REPO/bin/optimize_tiling_maps" ]; then echo "cannot find the repo at $REPO: submit from the repo root or set SKYTILING_REPO"; exit 1; fi
POWER=${1:-1}
ITERS=${2:-300}
PREFIX=${3:-stripes_p${POWER}_}
RECTS=${4:-$REPO/data/subaru3/niji_stripes_2p8_hsc.csv}; [ -f "$RECTS" ] || RECTS=$REPO/$RECTS
RUNDIR=${SKYTILING_RUNDIR:-$SCRATCH/skytiling/hsc_stripes}
mkdir -p "$RUNDIR"; cd "$RUNDIR"
module load python
SKYTILING_PY=${SKYTILING_PY:-$(which python)}
export NCPUS=${SLURM_CPUS_PER_TASK:-128}
NWORK=$(( NCPUS / 2 )); [ $NWORK -lt 1 ] && NWORK=1
DATA=$REPO/data/subaru3
# all runs on the same rectangle file share one set of randoms (generated by the first)
RANDOMS=$RUNDIR/randoms_$(basename "$RECTS" .csv)_4000000.fits
if [ -f "$RANDOMS" ]; then RANDARG="--randoms $RANDOMS"; else RANDARG="--num-randoms 4000000"; fi
$SKYTILING_PY -u "$REPO/bin/optimize_tiling_maps" -t $DATA/hsc_mbq1_throughput.fits \
    --rects "$RECTS" --interior-margin 0.75 $RANDARG \
    --init-lattice 1.299,1.125 --init-offsets "12.2,19.5 -19.5,12.2 -12.2,-19.5 19.5,-12.2" \
    --objective cv --cv-power $POWER \
    --workers $NWORK --max-drift 0.75 --moves-per-tile 4 --delta-rot 10 \
    --iters $ITERS --delta 0.1 --shrink 0.99 --seed 1 --plot --ra-center 180 --dec-center 0.68 --diameter 6 -o "$PREFIX"
# the randoms file is written as <PREFIX>randoms_4000000.fits by the first run; keep it under the shared name
[ -f "$RANDOMS" ] || cp "${PREFIX}randoms_4000000.fits" "$RANDOMS"
